### ISSUE TITLE
Disable the consistent-return rule

### ISSUE THREAD

**Issue by ryansobol** [ryansobol/eslint-config-ryansobol#43]
The [consistent-return](http://eslint.org/docs/rules/consistent-return) rule is intended to catch errors when a function returns an unexpected type of data like `undefined`. However, I find myself often disabling the rule for callback functions that use guard clauses. This indicates that enabling the rule goes against the philosophy "equip developers with powerful semantics". Therefore, the rule will be disabled.

**Comment by jackson-sandland** [comment]
How do you disable the rule?

**Comment by maksimhodasevich** [comment]
/* eslint consistent-return: off */

**Comment by dogfrogfog** [comment]
> How do you disable the rule?

/* eslint consistent-return: off */
